console.log("b2_new_file")
console.log("remote edit")
console.log("remote edit")
console.log("remote edit")
console.log("remote edit")
console.log("remote edit")
console.log("remote edit")
console.log("local edit")
console.log("remote edit")
console.log("remote edit")
console.log("remote edit")
console.log("remote edit")
console.log("remote edit")
console.log("remote edit")
console.log("new line")
