name: pr request reviewer reminder
on:
  schedule:
    # Check reviews every weekday at 1500 hrs
    - cron: '29 22 * * 1-5'

jobs:
  pull-request-reviewer-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: tommykw/pull-request-reviewer-reminder-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reminder_message: 'Two business days has passed since the review requested, please prioritize this PR. Or update pr status accordingly'
          review_turnaround_hours: 0
